require("hamm.plugins-setup")
require("hamm.core.options")
require("hamm.core.keymaps")
require("hamm.core.colorscheme")
require("hamm.plugins.treesitter")
require("hamm.plugins.lsp.mason")
require("hamm.plugins.lsp.lspsaga")
require("hamm.plugins.lsp.lspconfig")
require("hamm.plugins.lsp.null-ls")
require("hamm.plugins.comment")
require("hamm.plugins.nvim-tree")
require("hamm.plugins.lualine")
require("hamm.plugins.telescope")
require("hamm.plugins.nvim-cmp")
require("hamm.plugins.gitsigns")
--require("hamm.plugins.barbar")
require("hamm.plugins.dap.nvim-dap-ui")
require("hamm.plugins.dap.nvim-dap-virtual-text")
require("hamm.plugins.dap.nvim-dap-go")
require("hamm.plugins.dap.nvim-dap-python")
require("hamm.plugins.dap.nvim-dap-rust")
-- execute last
-- require("hamm.plugins.nvim-transparent")
require("hamm.core.colors")
require("hamm.plugins.nvim-colorizer")
