require("hamm.plugins-setup")
require("hamm.core.options")
require("hamm.core.keymaps")
require("hamm.core.colorscheme")
require("hamm.plugins.treesitter")
-- lsp
require("hamm.plugins.lsp.null-ls")
require("hamm.plugins.lsp.lsp-setup")
-- require("hamm.plugins.lsp.flutter-tools")
require("hamm.plugins.comment")
require("hamm.plugins.lualine")
require("hamm.plugins.telescope")
require("hamm.plugins.gitsigns")
require("hamm.plugins.scope")
require("hamm.plugins.oil")
require("hamm.plugins.bufresize")
require("hamm.plugins.colorizer")
-- dap
require("hamm.plugins.dap.nvim-dap-ui")
-- require("hamm.plugins.dap.nvim-dap-virtual-text")
require("hamm.plugins.dap.nvim-dap-go")
require("hamm.plugins.dap.nvim-dap-python")
require("hamm.plugins.dap.nvim-dap-rust")
require("hamm.plugins.dap.nvim-dap-dotnet")
-- execute last
require("hamm.core.colors")
