-- vim.cmd("colorscheme horizon")
vim.cmd("colorscheme catppuccin")
-- vim.cmd("colorscheme kanagawa")
-- vim.cmd("colorscheme gruvbox-material")
-- vim.cmd("colorscheme rose-pine-moon")
-- vim.cmd("colorscheme monokai-pro")

-- local status, _ = pcall(vim.cmd, "colorscheme horizon")
-- local status, _ = pcall(vim.cmd, "colorscheme catppuccin")
-- local status, _ = pcall(vim.cmd, "colorscheme kanagawa")
-- if not status then
-- 	print("Colorscheme not found!")
-- 	return
-- end
-- disable semantic highlighting added in neovim 0.9
-- source: https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/
-- local links = {
-- 	["@lsp.type.namespace"] = "@namespace",
-- 	["@lsp.type.type"] = "@type",
-- 	["@lsp.type.class"] = "@type",
-- 	["@lsp.type.enum"] = "@type",
-- 	["@lsp.type.interface"] = "@type",
-- 	["@lsp.type.struct"] = "@structure",
-- 	["@lsp.type.parameter"] = "@parameter",
-- 	["@lsp.type.variable"] = "@variable",
-- 	["@lsp.type.property"] = "@property",
-- 	["@lsp.type.enummember"] = "@constant",
-- 	["@lsp.type.function"] = "@function",
-- 	["@lsp.type.method"] = "@method",
-- 	["@lsp.type.macro"] = "@macro",
-- 	["@lsp.type.decorator"] = "@function",
-- }
-- for newgroup, oldgroup in pairs(links) do
-- 	vim.api.nvim_set_hl(0, newgroup, { link = oldgroup, default = true })
-- end
